name: patrol_application
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_linkify: ^6.0.0
  icons_launcher: ^2.1.7
  loading_animation_widget: ^1.2.1
  logger: ^2.2.0
  mask_text_input_formatter: ^2.9.0
  permission_handler: ^11.3.1
  shamsi_date: ^1.0.2
  shared_preferences: ^2.2.3
  url_launcher: ^6.2.6
  mobile_scanner: 3.5.6
  nfc_manager: 3.3.0
  cupertino_icons: ^1.0.2
  go_router: 12.1.3
  geolocator: 10.0.0
  app_settings: 5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/iran_sans/iran_sans_mobile.ttf
        - asset: assets/fonts/iran_sans/iran_sans_mobile_black.ttf
          weight: 900
        - asset: assets/fonts/iran_sans/iran_sans_mobile_bold.ttf
          weight: 800
        - asset: assets/fonts/iran_sans/iran_sans_mobile_black.ttf
          weight: 700
        - asset: assets/fonts/iran_sans/iran_sans_mobile_medium.ttf
          weight: 500
        - asset: assets/fonts/iran_sans/iran_sans_mobile.ttf
          weight: 400
        - asset: assets/fonts/iran_sans/iran_sans_mobile_light.ttf
          weight: 300
        - asset: assets/fonts/iran_sans/iran_sans_mobile_ultra_light.ttf
          weight: 200
